project:
  type: book
  output-dir: _book
  resources:
  - '!projects/**'
book:
  title: Структура учебного курса
  chapters:
  - index.qmd
  - tasks/index.qmd
  - labs/01.qmd
format:
  html:
    theme: cosmo
    code-links:
    - text: Исходники группы
      icon: github
      href: https://github.com/Afonenko-Course-Tools/quarto-course/tree/demo-20261007-patch1/examples/course
lang: ru
course:
  id: demo-core
filters:
- course-core
- course-presentation
profile:
  default: full
  group:
  - - student
    - full
