import { dirname, fromFileUrl, join, relative, toFileUrl } from "stdlib/path";
const repo = dirname(dirname(fromFileUrl(import.meta.url))),
  root = await Deno.makeTempDir({ prefix: "native-generated-resources-" }),
  quarto = Deno.env.get("QUARTO") || "quarto";
const assert = (v: unknown, message: string) => {
  if (!v) throw Error(message);
};
async function run(args: string[]) {
  const result = await new Deno.Command(quarto, {
    args,
    cwd: root,
    stdout: "piped",
    stderr: "piped",
  }).output();
  assert(
    result.success,
    new TextDecoder().decode(result.stdout) +
      new TextDecoder().decode(result.stderr),
  );
}
try {
  await run(["add", repo, "--no-prompt"]);
  await Deno.writeTextFile(
    join(root, "_quarto.yml"),
    `project:
  type: website
  output-dir: _site-default
  render: [nested/index.qmd]
  pre-render: _extensions/course-core/entrypoints/pre.ts
  post-render: _extensions/course-core/entrypoints/post.ts
course:
  id: native-plot
filters: [course-core]
exercise-bank: true
exercise-statement-visibility: open
format: html
execute:
  freeze: auto
`,
  );
  for (const view of ["student", "full"]) {
    await Deno.writeTextFile(
      join(root, `_quarto-${view}.yml`),
      `project:\n  output-dir: _site-${view}\ncourse:\n  view: ${view}\n`,
    );
  }
  await Deno.mkdir(join(root, "nested"));
  await Deno.mkdir(join(root, "assets"));
  await Deno.writeTextFile(
    join(root, "assets/shared.svg"),
    '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"><circle cx="10" cy="10" r="8"/></svg>',
  );
  await Deno.writeTextFile(
    join(root, "nested/student-only.txt"),
    "STUDENT_PROFILE_RESOURCE",
  );
  await Deno.writeTextFile(
    join(root, "nested/index.qmd"),
    `---
assessment:
  kind: lab
---
# Generated plot {#sec-generated}

::: {#exr-plot course-role="independent-study" difficulty="introductory" time=10}
Interpret the generated diagram.

![Shared relative asset](../assets/shared.svg)

~~~{r}
#| label: public-plot
#| echo: false
plot(1:3, 1:3)
~~~

[Plot copy](index_files/figure-html/public-plot-1.png?download=1#figure)

::: {.content-visible when-profile=student}
STUDENT_PROFILE_ONLY [Student file](student-only.txt)
:::
:::

:::: {.content-visible when-profile=full}
::: {#exr-private course-role="control" difficulty="advanced" time=10}
PRIVATE_PLOT

~~~{r}
#| label: private-plot
#| echo: false
plot(4:6, 6:4)
~~~
:::
::::

::: {.task-items}
1. @exr-plot
:::
`.replaceAll("~~~", "```"),
  );
  const { loadNativeRun } = await import(
    toFileUrl(
      join(root, "_extensions/course-core/infrastructure/native-run.ts"),
    ).href
  );
  const { buildBodies } = await import(
    toFileUrl(join(root, "_extensions/course-core/body-export/producer.ts"))
      .href
  );
  const { evaluateResources } = await import(
    toFileUrl(join(root, "_extensions/course-core/infrastructure/resources.ts"))
      .href
  );
  let freezeBytes: string | undefined;
  for (const view of ["default", "student", "full", "student"]) {
    await run(view === "default" ? ["render"] : ["render", "--profile", view]);
    const result = await loadNativeRun(
        root,
        view === "default" ? {} : { view },
      ),
      doc = result.documents[0];
    if (view === "default") {
      assert(
        !doc.resources.projectedUses.includes("student-only.txt"),
        "default public projection invented student profile",
      );
    }
    const bodies = await buildBodies(doc, {
      projectRoot: root,
      includeClosed: view === "full",
    });
    const privateOutput = join(
      root,
      `_site-${view}/nested/index_files/figure-html/private-plot-1.png`,
    );
    let privatePresent = false;
    try {
      privatePresent = (await Deno.stat(privateOutput)).isFile;
    } catch (e) {
      if (!(e instanceof Deno.errors.NotFound)) throw e;
    }
    assert(
      privatePresent === (view === "full"),
      "native student output retains hidden generated bytes or full lost them",
    );
    const sharedOutput = join(root, `_site-${view}/assets/shared.svg`);
    assert(
      (await Deno.stat(sharedOutput)).isFile,
      "public parent-relative asset deleted from native output",
    );
    const resources = bodies.publicPackage.resources;
    assert(
      resources.length === (view === "default" ? 2 : 3) &&
        resources.some((r: any) =>
          r.target === "nested/index_files/figure-html/public-plot-1.png" &&
          atob(r.data).length > 100
        ),
      "Current native plot bytes/target missing from public Body",
    );
    const condition = JSON.stringify(
      bodies.publicPackage.questions[0].condition,
    );
    assert(
      condition.includes(
        "nested/index_files/figure-html/public-plot-1.png?download=1#figure",
      ),
      "query/fragment rewritten incorrectly",
    );
    assert(
      !JSON.stringify(bodies.publicPackage).includes("private-plot") &&
        !JSON.stringify(bodies.publicPackage).includes("PRIVATE_PLOT"),
      "private generated resource leaked",
    );
    const freeze = await Deno.readTextFile(
      join(root, "_freeze/nested/index/execute-results/html.json"),
    );
    if (freezeBytes) {
      assert(
        freeze === freezeBytes,
        "native freeze cache changed across audience renders",
      );
    }
    freezeBytes = freeze;
    const privateFile = doc.resources.capturedFiles.find((f: any) =>
      f.source.endsWith("private-plot-1.png")
    );
    if (privateFile) {
      let denied = false;
      try {
        await evaluateResources({
          facts: [doc.resources],
          selected: [relative(root, privateFile.output)],
          projectRoot: root,
        });
      } catch {
        denied = true;
      }
      assert(denied, "private generated output alias exposed");
    }
    // A missing-at-filter resource never becomes eligible merely because output retains it.
    await Deno.writeTextFile(
      join(root, `_site-${view}/retained.png`),
      "OLD_RESOURCE",
    );
    let missingDenied = false;
    try {
      await evaluateResources({
        facts: [{
          ...doc.resources,
          rawUses: ["retained.png"],
          projectedUses: ["retained.png"],
          effectiveBase: root,
        }],
        selected: ["retained.png"],
        projectRoot: root,
      });
    } catch {
      missingDenied = true;
    }
    assert(missingDenied, "unobserved retained output accepted");
    const capture = doc.resources.capturedFiles.find((f: any) =>
      f.source.endsWith("public-plot-1.png")
    );
    await Deno.writeTextFile(capture.output, "STALE_DIFFERENT_PLOT");
    let changedDenied = false;
    try {
      await buildBodies(doc, {
        projectRoot: root,
        includeClosed: view === "full",
      });
    } catch {
      changedDenied = true;
    }
    assert(changedDenied, "nonmatching native output bytes accepted");
    console.log(
      "PASS installed generated plot Body, privacy, suffix, current bytes and freeze",
      view,
    );
  }
} finally {
  await Deno.remove(root, { recursive: true });
}
