import { dirname, fromFileUrl, join, toFileUrl } from "stdlib/path";
const repo = dirname(dirname(fromFileUrl(import.meta.url)));
const root = await Deno.makeTempDir({ prefix: "acceptance-plot-body-" });
const quarto = Deno.env.get("QUARTO") || "quarto";
async function run(args: string[]) {
  const r = await new Deno.Command(quarto, {
    args,
    cwd: root,
    stdout: "piped",
    stderr: "piped",
  }).output();
  if (!r.success) {
    throw Error(
      new TextDecoder().decode(r.stdout) + new TextDecoder().decode(r.stderr),
    );
  }
}
try {
  await run(["add", repo, "--no-prompt"]);
  await Deno.writeTextFile(
    join(root, "_quarto.yml"),
    "project:\n  type: website\n  render: [index.qmd]\n  pre-render: _extensions/course-core/entrypoints/pre.ts\n  post-render: _extensions/course-core/entrypoints/post.ts\ncourse:\n  id: native-plot\nfilters: [course-core]\nformat:\n  pdf:\n    pdf-engine: xelatex\nexecute:\n  freeze: auto\n",
  );
  for (const view of ["student", "full"]) {
    await Deno.writeTextFile(
      join(root, `_quarto-${view}.yml`),
      `project:\n  output-dir: _site-${view}\ncourse:\n  view: ${view}\n`,
    );
  }
  await Deno.writeTextFile(
    join(root, "index.qmd"),
    '---\nassessment:\n  kind: test\n---\n# Generated plot {#sec-generated}\n\n::: {#exr-plot course-role="independent-study" difficulty="introductory"}\nInterpret the generated diagram.\n\n```{r}\n#| echo: false\nplot(1:3, 1:3)\n```\n\n::: {.content-visible when-profile=full}\nPRIVATE_PDF_PLOT\n\n```{r}\n#| label: private-pdf\n#| echo: false\nplot(7:9,9:7)\n```\n:::\n:::\n\n::: {.task-items}\n1. @exr-plot\n:::\n',
  );
  const { loadNativeRun } = await import(
    toFileUrl(
      join(root, "_extensions/course-core/infrastructure/native-run.ts"),
    ).href
  );
  const { buildBodies } = await import(
    toFileUrl(join(root, "_extensions/course-core/body-export/producer.ts"))
      .href
  );
  for (const view of ["student", "full", "student"]) {
    await run(["render", "--profile", view]);
    const result = await loadNativeRun(root, { view });
    if (result.documents[0].document.output !== "index.pdf") {
      throw Error("NativeRun must name the actual final PDF");
    }
    const bodies = await buildBodies(result.documents[0], {
      projectRoot: root,
      includeClosed: view === "full",
    });
    if (
      !bodies.publicPackage.resources.some((r: any) =>
        atob(r.data).length > 100
      )
    ) throw Error("Native plot bytes missing from public body");
    const captures = result.documents[0].resources.capturedFiles;
    const hidden = captures.find((f: any) => f.source.includes("private-pdf"));
    if (!hidden || Boolean(hidden.capture) !== (view === "full")) {
      throw Error("public PDF sidecar retained hidden generated bytes");
    }
    if (JSON.stringify(bodies.publicPackage).includes("private-pdf")) {
      throw Error("public PDF Body exposed private resource");
    }
    const capture = captures.find((f: any) =>
      !f.source.includes("private-pdf") && f.capture
    );
    const bytes = await Deno.readFile(capture.capture);
    const rejects = async () => {
      let rejected = false;
      try {
        await buildBodies(result.documents[0], {
          projectRoot: root,
          includeClosed: view === "full",
        });
      } catch {
        rejected = true;
      }
      if (!rejected) {
        throw Error("missing, changed or escaping PDF capture accepted");
      }
    };
    await Deno.remove(capture.capture);
    await rejects();
    await Deno.writeTextFile(capture.capture, "STALE_CAPTURE");
    await rejects();
    await Deno.remove(capture.capture);
    await Deno.symlink("/etc/hosts", capture.capture);
    await rejects();
    await Deno.remove(capture.capture);
    await Deno.writeFile(capture.capture, bytes);
    console.log(
      "PASS generated native PDF Body, public capture privacy and missing/tampered/escaping capture guards",
      view,
      bodies.publicPackage.resources.map((r: any) => r.target),
    );
  }
  console.log(
    "PASS actual installed native plot/generated bytes/student-full-student",
    root,
  );
} finally {
  await Deno.remove(root, { recursive: true });
}
